// 원본 shared/NotificationPart.cshtml 마크업 verbatim
export const NOTIFICATION_HTML = `<div class="modal fade modal-inner-scroll pointevent__unset show" id="alramModal" tabindex="-1" aria-modal="true" role="dialog" style="display: none;"><div class="modal-dialog"><div class="notification-wrap"><section class="notification-wrap-popup     active"><div class="alert alert-warning alert-dismissible fade show" role="alert"><span class="material-symbols-sharp">error</span><div class="msg">목록의 체크박스를 선택하고 액션버튼(삭제 및 읽음으로 표시)을 눌러주세요.</div><button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button></div><div class="notification-wrap-popup-tabs"><button class="today active">오늘</button><button class="all">전체 알림</button><div class="button-area"><div class="button-area-button" id="changeNotificationButton"><span class="material-symbols-sharp"></span></div><button class="closeBtn button-area-button"><span class="material-symbols-sharp">
                                close
                            </span></button></div></div><div id="notificationToday" class="notification-body active"><div class="notification-wrap-popup-info"><div>
                            선택된 알림
                            <strong>개</strong>
                            / 총 개
                        </div><div><button>읽음으로 표시</button></div></div><ul class="notification-wrap-popup-board"><li class="header"><div><input type="checkbox" class="checkbox-blue mark-valid" id="todayCheckAll" /><span>내용</span></div><div>일시</div></li><template><li class="checked"><div><input type="checkbox" class="checkbox-blue mark-valid" name="f_todaycheck" /><p></p><span class="notification-new">N</span></div><div></div></li><li><div><input type="checkbox" class="checkbox-blue mark-valid" disabled /><p></p><span class="notification-new">N</span></div><div></div></li></template></ul><ul class="notification-wrap-popup-board empty"><li class="notification-wrap-popup-empty"><picture><img src="/assets/student/images/notification/notifications.svg" /><blockquote>새로운 알림이 없습니다.</blockquote></picture></li></ul><div class="d-flex justify-content-center mt-16"><pagination></pagination></div></div><div id="notificationAll" class="notification-body"><div class="notification-wrap-popup-info"><div>
                            선택된 알림
                            <strong>개</strong>
                            / 총 개
                        </div><div><button>읽음으로 표시</button></div></div><ul class="notification-wrap-popup-board"><li class="header"><div><input type="checkbox" class="checkbox-blue mark-valid" id="checkAll" /><span>내용</span></div><div>일시</div></li><template><li class="checked"><div><input type="checkbox" class="checkbox-blue mark-valid" name="f_check" /><p></p><span class="notification-new">N</span></div><div></div></li><li><div><input type="checkbox" class="checkbox-blue mark-valid" disabled /><p></p><span class="notification-new">N</span></div><div></div></li></template></ul><ul class="notification-wrap-popup-board empty"><li class="notification-wrap-popup-empty"><picture><img src="/assets/student/images/notification/notifications.svg" /><blockquote>새로운 알림이 없습니다.</blockquote></picture></li></ul><div class="d-flex justify-content-center mt-16"><pagination></pagination></div></div></section></div></div></div>`;
